# Generated by Django 5.0.6 on 2024-07-02 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_soccerplayer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='DateAdded',
            new_name='dateadded',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='DateUpdated',
            new_name='dateupdated',
        ),
    ]
