# Generated by Django 5.0.6 on 2024-07-06 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_slide'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='slide',
            table='Slide',
        ),
    ]
