# Generated by Django 5.0.6 on 2024-07-06 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_dateadded_product_dateadded_and_more'),
        ('app', '0005_alter_slide_table'),
    ]

    operations = [
    ]
