# Generated by Django 5.0.6 on 2024-07-13 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_dimaccount_dimchannel_dimcurrency_dimcustomer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DimAccount',
        ),
        migrations.DeleteModel(
            name='DimChannel',
        ),
        migrations.DeleteModel(
            name='DimCurrency',
        ),
        migrations.DeleteModel(
            name='DimCustomer',
        ),
        migrations.DeleteModel(
            name='DimDate',
        ),
        migrations.DeleteModel(
            name='DimEmployee',
        ),
        migrations.DeleteModel(
            name='DimEntity',
        ),
        migrations.DeleteModel(
            name='DimGeography',
        ),
        migrations.DeleteModel(
            name='DimMachine',
        ),
        migrations.DeleteModel(
            name='DimOutage',
        ),
        migrations.DeleteModel(
            name='DimProduct',
        ),
        migrations.DeleteModel(
            name='DimProductCategory',
        ),
        migrations.DeleteModel(
            name='DimProductSubcategory',
        ),
        migrations.DeleteModel(
            name='DimPromotion',
        ),
        migrations.DeleteModel(
            name='DimSalesTerritory',
        ),
        migrations.DeleteModel(
            name='DimScenario',
        ),
        migrations.DeleteModel(
            name='DimStore',
        ),
        migrations.DeleteModel(
            name='FactExchangeRate',
        ),
        migrations.DeleteModel(
            name='FactInventory',
        ),
        migrations.DeleteModel(
            name='FactITMachine',
        ),
        migrations.DeleteModel(
            name='FactITSLA',
        ),
        migrations.DeleteModel(
            name='FactOnlineSales',
        ),
        migrations.DeleteModel(
            name='FactSales',
        ),
        migrations.DeleteModel(
            name='FactSalesQuota',
        ),
        migrations.DeleteModel(
            name='FactStrategyPlan',
        ),
    ]
