# Generated by Django 5.0.6 on 2024-07-13 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_customer_products_supplier_order_orderdetail_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Warehouse_Products',
        ),
    ]
